#!/bin/bash
# Setup the enviroment

sudo apt-update
sudo apt-upgrade

#packages & libraries
sudo apt-get install vim git curl gcc bson htop zsh build-essential cmake python-dev python3-dev  -y

#set up zsh 
chsh -s $(which zsh)

#Oh my zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Node setup
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt-get install -y build-essential

#Go gvm package 
zsh < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)

source /home/daniel/.gvm/scripts/gvm

gvm install go1.4 -B
gvm use go1.4
export GOROOT_BOOTSTRAP=$GOROOT
gvm install go1.5

#Postgresql
sudo apt-get install postgresql postgresql-contrib libpq-dev

#tmux
sudo apt install -y libevent-dev libncurses-dev pkg-config
sudo apt install tmux 


#docker
sudo curl -sSL https://get.docker.com/ | sh


#mariaDB
sudo apt-get install software-properties-common
sudo apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0xF1656F24C74CD1D8
sudo add-apt-repository 'deb [arch=amd64,i386] https://mirrors.evowise.com/mariadb/repo/10.1/ubuntu xenial main'
sudo apt-get update
sudo apt-get install mariadb-server, grcat
